services:
  - type: web
    name: tp-backend
    env: python
    plan: free
    region: oregon  # o southamerica-east1 si est√° disponible
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.back:app --reload"
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: ENV
        value: production
      - key: API_KEY
        sync: false  # puedes agregarla manualmente en el panel de Render

    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1
