services:
  - type: web
    name: tp-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend

    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "uvicorn back:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: ENV
        value: production
      - key: API_KEY
        sync: false

    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1
